AllCops:
  Exclude:
    - 'bin/**/*'
    - 'node_modules/**/*'

Layout/LineLength:
  Max: 100
  IgnoredPatterns:
    - '\A\s*#'

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Metrics/BlockLength:
  Exclude:
    - 'db/**/*'
    - 'spec/**/*'

Metrics/MethodLength:
  Exclude:
    - 'db/**/*'

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma
