AllCops:
  Exclude:
    - 'bin/**/*'
    - 'node_modules/**/*'

Layout/LineLength:
  Max: 100
  IgnoredPatterns:
    - '\A\s*#'

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
